#!/bin/bash

#PBS -P RDS-FEI-RICARDO_01-RW                
#PBS -l select=9:ncpus=32:mpiprocs=288:mem=20GB
#PBS -l walltime=168:00:00
#PBS -N MPI_Ricardo_Simulator
#PBS -m abe
#PBS -M xwan0069@uni.sydney.edu.au

module load python/3.8.2 magma/2.5.3 pandas/2.0.3 gurobi/9.1.2
source /project/RDS-FEI-RICARDO_01-RW/envs/torchenv/bin/activate
cd /project/RDS-FEI-RICARDO_01-RW/RL_Simulator
mpirun -np 288 python RL_main.py> output.log 2> error.log