#!/bin/bash

#PBS -P RDS-FEI-RICARDO_01-RW                
#PBS -l select=1:ncpus=1:ngpus=1:mem=30GB
#PBS -l walltime=24:00:00
#PBS -N RL_Ricardo
#PBS -m abe
#PBS -M xwan0069@uni.sydney.edu.au

module load python/3.8.2 magma/2.5.3 pandas/2.0.3 gurobi/9.1.2
source /project/RDS-FEI-RICARDO_01-RW/envs/torchenv/bin/activate
cd /project/RDS-FEI-RICARDO_01-RW/RL_Simulator
python RL_main.py> output.log 2> error.log